#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PushwooshSample.Resource", IsApplication=true)]

namespace PushwooshSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int pw_logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int general_status = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int image = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int root = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int status = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int submit_tags = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int tag_int = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int tag_string = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int text_push = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int second = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int push_sound = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int app_name = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int general_status = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int on_message = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int pw_logo = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int registered = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int registered_error = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int second_activity = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int status_error = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int status_init_error = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int status_int_parse_error = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int status_ready = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int status_started = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int status_success = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int submit_tags = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int tag_int = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int tag_int_hint = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int tag_string = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int tag_string_hint = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int tags_status = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int unregistered = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int unregistered_error = 2131034130;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Text = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
