#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PushwooshSample.Resource", IsApplication=true)]

namespace PushwooshSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int buttonSize = 2130771985;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010016
			public const int circleCrop = 2130771990;
			
			// aapt resource value: 0x7f010012
			public const int colorScheme = 2130771986;
			
			// aapt resource value: 0x7f010015
			public const int imageAspectRatio = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int imageAspectRatioAdjust = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010013
			public const int scopeUris = 2130771987;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000e
			public const int common_action_bar_splitter = 2131034126;
			
			// aapt resource value: 0x7f050017
			public const int common_google_signin_btn_text_dark = 2131034135;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_signin_btn_text_dark_default = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int common_google_signin_btn_text_dark_disabled = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int common_google_signin_btn_text_dark_focused = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int common_google_signin_btn_text_dark_pressed = 2131034128;
			
			// aapt resource value: 0x7f050018
			public const int common_google_signin_btn_text_light = 2131034136;
			
			// aapt resource value: 0x7f050013
			public const int common_google_signin_btn_text_light_default = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int common_google_signin_btn_text_light_disabled = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int common_google_signin_btn_text_light_focused = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int common_google_signin_btn_text_light_pressed = 2131034132;
			
			// aapt resource value: 0x7f050019
			public const int common_plus_signin_btn_text_dark = 2131034137;
			
			// aapt resource value: 0x7f050006
			public const int common_plus_signin_btn_text_dark_default = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int common_plus_signin_btn_text_dark_disabled = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_plus_signin_btn_text_dark_focused = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int common_plus_signin_btn_text_dark_pressed = 2131034119;
			
			// aapt resource value: 0x7f05001a
			public const int common_plus_signin_btn_text_light = 2131034138;
			
			// aapt resource value: 0x7f05000a
			public const int common_plus_signin_btn_text_light_default = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int common_plus_signin_btn_text_light_disabled = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_plus_signin_btn_text_light_focused = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int common_plus_signin_btn_text_light_pressed = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int place_autocomplete_prediction_primary_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int place_autocomplete_prediction_primary_text_highlight = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int place_autocomplete_prediction_secondary_text = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int place_autocomplete_search_hint = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int place_autocomplete_search_text = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int place_autocomplete_separator = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int place_autocomplete_button_padding = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int place_autocomplete_powered_by_google_height = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int place_autocomplete_powered_by_google_start = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int place_autocomplete_prediction_height = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int place_autocomplete_prediction_horizontal_margin = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int place_autocomplete_prediction_primary_text = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int place_autocomplete_prediction_secondary_text = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int place_autocomplete_progress_horizontal_margin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int place_autocomplete_progress_size = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int place_autocomplete_separator_start = 2131099655;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_ic_googleplayservices = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_plus_signin_btn_icon_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_light_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_text_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_text_dark_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_light_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_launcher = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int places_ic_clear = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int places_ic_search = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int powered_by_google_dark = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int powered_by_google_light = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int pw_logo = 2130837551;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000b
			public const int adjust_height = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int adjust_width = 2131361804;
			
			// aapt resource value: 0x7f0a0008
			public const int auto = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int dark = 2131361801;
			
			// aapt resource value: 0x7f0a000e
			public const int general_status = 2131361806;
			
			// aapt resource value: 0x7f0a0000
			public const int hybrid = 2131361792;
			
			// aapt resource value: 0x7f0a0005
			public const int icon_only = 2131361797;
			
			// aapt resource value: 0x7f0a0013
			public const int image = 2131361811;
			
			// aapt resource value: 0x7f0a000a
			public const int light = 2131361802;
			
			// aapt resource value: 0x7f0a0001
			public const int none = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int normal = 2131361794;
			
			// aapt resource value: 0x7f0a0016
			public const int place_autocomplete_clear_button = 2131361814;
			
			// aapt resource value: 0x7f0a0018
			public const int place_autocomplete_powered_by_google = 2131361816;
			
			// aapt resource value: 0x7f0a001a
			public const int place_autocomplete_prediction_primary_text = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int place_autocomplete_prediction_secondary_text = 2131361819;
			
			// aapt resource value: 0x7f0a0019
			public const int place_autocomplete_progress = 2131361817;
			
			// aapt resource value: 0x7f0a0014
			public const int place_autocomplete_search_button = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int place_autocomplete_search_input = 2131361813;
			
			// aapt resource value: 0x7f0a0017
			public const int place_autocomplete_separator = 2131361815;
			
			// aapt resource value: 0x7f0a000d
			public const int root = 2131361805;
			
			// aapt resource value: 0x7f0a0003
			public const int satellite = 2131361795;
			
			// aapt resource value: 0x7f0a0006
			public const int standard = 2131361798;
			
			// aapt resource value: 0x7f0a000f
			public const int status = 2131361807;
			
			// aapt resource value: 0x7f0a0012
			public const int submit_tags = 2131361810;
			
			// aapt resource value: 0x7f0a0010
			public const int tag_int = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int tag_string = 2131361809;
			
			// aapt resource value: 0x7f0a0004
			public const int terrain = 2131361796;
			
			// aapt resource value: 0x7f0a001c
			public const int text_push = 2131361820;
			
			// aapt resource value: 0x7f0a0007
			public const int wide = 2131361799;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int place_autocomplete_fragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int place_autocomplete_item_powered_by_google = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int place_autocomplete_item_prediction = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int place_autocomplete_progress = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int second = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int push_sound = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070027
			public const int app_name = 2131165223;
			
			// aapt resource value: 0x7f07001f
			public const int auth_google_play_services_client_facebook_display_name = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int auth_google_play_services_client_google_display_name = 2131165214;
			
			// aapt resource value: 0x7f070017
			public const int common_google_play_services_api_unavailable_text = 2131165207;
			
			// aapt resource value: 0x7f070009
			public const int common_google_play_services_enable_button = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int common_google_play_services_enable_text = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int common_google_play_services_enable_title = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int common_google_play_services_install_button = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int common_google_play_services_install_text_phone = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int common_google_play_services_install_text_tablet = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int common_google_play_services_install_title = 2131165187;
			
			// aapt resource value: 0x7f070012
			public const int common_google_play_services_invalid_account_text = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int common_google_play_services_invalid_account_title = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int common_google_play_services_network_error_text = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int common_google_play_services_network_error_title = 2131165199;
			
			// aapt resource value: 0x7f070002
			public const int common_google_play_services_notification_ticker = 2131165186;
			
			// aapt resource value: 0x7f07001b
			public const int common_google_play_services_restricted_profile_text = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int common_google_play_services_restricted_profile_title = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int common_google_play_services_sign_in_failed_text = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int common_google_play_services_sign_in_failed_title = 2131165208;
			
			// aapt resource value: 0x7f070020
			public const int common_google_play_services_unknown_issue = 2131165216;
			
			// aapt resource value: 0x7f070014
			public const int common_google_play_services_unsupported_text = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int common_google_play_services_unsupported_title = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int common_google_play_services_update_button = 2131165205;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_play_services_update_text = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_play_services_update_title = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int common_google_play_services_updating_text = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int common_google_play_services_updating_title = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_play_services_wear_update_text = 2131165196;
			
			// aapt resource value: 0x7f070016
			public const int common_open_on_phone = 2131165206;
			
			// aapt resource value: 0x7f07001c
			public const int common_signin_button_text = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int common_signin_button_text_long = 2131165213;
			
			// aapt resource value: 0x7f07002f
			public const int general_status = 2131165231;
			
			// aapt resource value: 0x7f070034
			public const int on_message = 2131165236;
			
			// aapt resource value: 0x7f070001
			public const int place_autocomplete_clear_button = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int place_autocomplete_search_hint = 2131165184;
			
			// aapt resource value: 0x7f070028
			public const int pw_logo = 2131165224;
			
			// aapt resource value: 0x7f070030
			public const int registered = 2131165232;
			
			// aapt resource value: 0x7f070032
			public const int registered_error = 2131165234;
			
			// aapt resource value: 0x7f070035
			public const int second_activity = 2131165237;
			
			// aapt resource value: 0x7f070024
			public const int status_error = 2131165220;
			
			// aapt resource value: 0x7f070021
			public const int status_init_error = 2131165217;
			
			// aapt resource value: 0x7f070025
			public const int status_int_parse_error = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int status_ready = 2131165222;
			
			// aapt resource value: 0x7f070022
			public const int status_started = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int status_success = 2131165219;
			
			// aapt resource value: 0x7f07002d
			public const int submit_tags = 2131165229;
			
			// aapt resource value: 0x7f070029
			public const int tag_int = 2131165225;
			
			// aapt resource value: 0x7f07002b
			public const int tag_int_hint = 2131165227;
			
			// aapt resource value: 0x7f07002a
			public const int tag_string = 2131165226;
			
			// aapt resource value: 0x7f07002c
			public const int tag_string_hint = 2131165228;
			
			// aapt resource value: 0x7f07002e
			public const int tags_status = 2131165230;
			
			// aapt resource value: 0x7f070031
			public const int unregistered = 2131165233;
			
			// aapt resource value: 0x7f070033
			public const int unregistered_error = 2131165235;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int Text = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[]
			{
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
