#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PushwooshSample.Resource", IsApplication=true)]

namespace PushwooshSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010010
			public const int disableLayoutAnimation = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public const int font = 2130771981;
			
			// aapt resource value: 0x7f010006
			public const int fontProviderAuthority = 2130771974;
			
			// aapt resource value: 0x7f010009
			public const int fontProviderCerts = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int fontProviderFetchStrategy = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int fontProviderFetchTimeout = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int fontProviderPackage = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fontProviderQuery = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public const int fontStyle = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public const int fontWeight = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int identifier = 2130771983;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0b0000
			public const int abc_action_bar_embed_tabs = 2131427328;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f08000f
			public const int common_google_signin_btn_text_dark = 2131230735;
			
			// aapt resource value: 0x7f080000
			public const int common_google_signin_btn_text_dark_default = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int common_google_signin_btn_text_dark_disabled = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int common_google_signin_btn_text_dark_focused = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int common_google_signin_btn_text_dark_pressed = 2131230723;
			
			// aapt resource value: 0x7f080010
			public const int common_google_signin_btn_text_light = 2131230736;
			
			// aapt resource value: 0x7f080004
			public const int common_google_signin_btn_text_light_default = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int common_google_signin_btn_text_light_disabled = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int common_google_signin_btn_text_light_focused = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int common_google_signin_btn_text_light_pressed = 2131230727;
			
			// aapt resource value: 0x7f080011
			public const int common_google_signin_btn_tint = 2131230737;
			
			// aapt resource value: 0x7f08000b
			public const int notification_action_color_filter = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int notification_icon_bg_color = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int notification_material_background_media_default_color = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int primary_text_default_material_dark = 2131230729;
			
			// aapt resource value: 0x7f08000d
			public const int ripple_material_light = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int secondary_text_default_material_dark = 2131230730;
			
			// aapt resource value: 0x7f08000e
			public const int secondary_text_default_material_light = 2131230734;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0c0004
			public const int compat_button_inset_horizontal_material = 2131492868;
			
			// aapt resource value: 0x7f0c0005
			public const int compat_button_inset_vertical_material = 2131492869;
			
			// aapt resource value: 0x7f0c0006
			public const int compat_button_padding_horizontal_material = 2131492870;
			
			// aapt resource value: 0x7f0c0007
			public const int compat_button_padding_vertical_material = 2131492871;
			
			// aapt resource value: 0x7f0c0008
			public const int compat_control_corner_material = 2131492872;
			
			// aapt resource value: 0x7f0c0009
			public const int notification_action_icon_size = 2131492873;
			
			// aapt resource value: 0x7f0c000a
			public const int notification_action_text_size = 2131492874;
			
			// aapt resource value: 0x7f0c000b
			public const int notification_big_circle_margin = 2131492875;
			
			// aapt resource value: 0x7f0c0001
			public const int notification_content_margin_start = 2131492865;
			
			// aapt resource value: 0x7f0c000c
			public const int notification_large_icon_height = 2131492876;
			
			// aapt resource value: 0x7f0c000d
			public const int notification_large_icon_width = 2131492877;
			
			// aapt resource value: 0x7f0c0002
			public const int notification_main_column_padding_top = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int notification_media_narrow_margin = 2131492867;
			
			// aapt resource value: 0x7f0c000e
			public const int notification_right_icon_size = 2131492878;
			
			// aapt resource value: 0x7f0c0000
			public const int notification_right_side_padding_top = 2131492864;
			
			// aapt resource value: 0x7f0c000f
			public const int notification_small_icon_background_padding = 2131492879;
			
			// aapt resource value: 0x7f0c0010
			public const int notification_small_icon_size_as_large = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int notification_subtext_size = 2131492881;
			
			// aapt resource value: 0x7f0c0012
			public const int notification_top_pad = 2131492882;
			
			// aapt resource value: 0x7f0c0013
			public const int notification_top_pad_large_text = 2131492883;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_text_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_normal_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_normal_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int googleg_disabled_color_18 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int googleg_standard_color_18 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_launcher = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int notification_action_background = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int notification_bg = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int notification_bg_low = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int notification_bg_low_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int notification_bg_low_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int notification_bg_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int notification_bg_normal_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int notification_icon_background = 2130837533;
			
			// aapt resource value: 0x7f020022
			public const int notification_template_icon_bg = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int notification_template_icon_low_bg = 2130837539;
			
			// aapt resource value: 0x7f02001e
			public const int notification_tile_bg = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int notify_panel_notification_icon_bg = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int pw_default_loading_view_background = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int pw_logo = 2130837537;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001e
			public const int action0 = 2131296286;
			
			// aapt resource value: 0x7f09001b
			public const int action_container = 2131296283;
			
			// aapt resource value: 0x7f090022
			public const int action_divider = 2131296290;
			
			// aapt resource value: 0x7f09001c
			public const int action_image = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int action_text = 2131296285;
			
			// aapt resource value: 0x7f09002c
			public const int actions = 2131296300;
			
			// aapt resource value: 0x7f090006
			public const int adjust_height = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int adjust_width = 2131296263;
			
			// aapt resource value: 0x7f09000f
			public const int async = 2131296271;
			
			// aapt resource value: 0x7f09000c
			public const int auto = 2131296268;
			
			// aapt resource value: 0x7f090010
			public const int blocking = 2131296272;
			
			// aapt resource value: 0x7f09001f
			public const int cancel_action = 2131296287;
			
			// aapt resource value: 0x7f090027
			public const int chronometer = 2131296295;
			
			// aapt resource value: 0x7f090000
			public const int crash_reporting_present = 2131296256;
			
			// aapt resource value: 0x7f09000d
			public const int dark = 2131296269;
			
			// aapt resource value: 0x7f09002e
			public const int end_padder = 2131296302;
			
			// aapt resource value: 0x7f090011
			public const int forever = 2131296273;
			
			// aapt resource value: 0x7f090015
			public const int general_status = 2131296277;
			
			// aapt resource value: 0x7f090029
			public const int icon = 2131296297;
			
			// aapt resource value: 0x7f09002d
			public const int icon_group = 2131296301;
			
			// aapt resource value: 0x7f090009
			public const int icon_only = 2131296265;
			
			// aapt resource value: 0x7f09001a
			public const int image = 2131296282;
			
			// aapt resource value: 0x7f090028
			public const int info = 2131296296;
			
			// aapt resource value: 0x7f090012
			public const int italic = 2131296274;
			
			// aapt resource value: 0x7f09000e
			public const int light = 2131296270;
			
			// aapt resource value: 0x7f090001
			public const int line1 = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int line3 = 2131296258;
			
			// aapt resource value: 0x7f090021
			public const int media_actions = 2131296289;
			
			// aapt resource value: 0x7f090008
			public const int none = 2131296264;
			
			// aapt resource value: 0x7f090013
			public const int normal = 2131296275;
			
			// aapt resource value: 0x7f09002b
			public const int notification_background = 2131296299;
			
			// aapt resource value: 0x7f090024
			public const int notification_main_column = 2131296292;
			
			// aapt resource value: 0x7f090023
			public const int notification_main_column_container = 2131296291;
			
			// aapt resource value: 0x7f09002a
			public const int right_icon = 2131296298;
			
			// aapt resource value: 0x7f090025
			public const int right_side = 2131296293;
			
			// aapt resource value: 0x7f090014
			public const int root = 2131296276;
			
			// aapt resource value: 0x7f09000a
			public const int standard = 2131296266;
			
			// aapt resource value: 0x7f090016
			public const int status = 2131296278;
			
			// aapt resource value: 0x7f090020
			public const int status_bar_latest_event_content = 2131296288;
			
			// aapt resource value: 0x7f090019
			public const int submit_tags = 2131296281;
			
			// aapt resource value: 0x7f090017
			public const int tag_int = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int tag_string = 2131296280;
			
			// aapt resource value: 0x7f090003
			public const int text = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int text2 = 2131296260;
			
			// aapt resource value: 0x7f09002f
			public const int text_push = 2131296303;
			
			// aapt resource value: 0x7f090026
			public const int time = 2131296294;
			
			// aapt resource value: 0x7f090005
			public const int title = 2131296261;
			
			// aapt resource value: 0x7f09000b
			public const int wide = 2131296267;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070001
			public const int cancel_button_image_alpha = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int status_bar_notification_info_maxnum = 2131165186;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_action = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_action_tombstone = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_media_action = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_media_cancel_action = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_big_media = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_big_media_custom = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_template_big_media_narrow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_template_big_media_narrow_custom = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_custom_big = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_icon_group = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_lines_media = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_media = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_media_custom = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_part_chronometer = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_part_time = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int pw_default_loading_view = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int second = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int push_sound = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060021
			public const int app_name = 2131099681;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_enable_button = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_enable_text = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_enable_title = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_install_button = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_install_text = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_install_title = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_notification_ticker = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_unknown_issue = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_unsupported_text = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_update_button = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_update_text = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_update_title = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_updating_text = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int common_google_play_services_wear_update_text = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int common_open_on_phone = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int common_signin_button_text = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int common_signin_button_text_long = 2131099671;
			
			// aapt resource value: 0x7f060002
			public const int default_web_client_id = 2131099650;
			
			// aapt resource value: 0x7f060018
			public const int fcm_fallback_notification_channel_label = 2131099672;
			
			// aapt resource value: 0x7f060020
			public const int fcm_sender_id = 2131099680;
			
			// aapt resource value: 0x7f060003
			public const int firebase_database_url = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int gcm_defaultSenderId = 2131099648;
			
			// aapt resource value: 0x7f060029
			public const int general_status = 2131099689;
			
			// aapt resource value: 0x7f060004
			public const int google_api_key = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int google_app_id = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int google_crash_reporting_api_key = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int google_storage_bucket = 2131099654;
			
			// aapt resource value: 0x7f06002e
			public const int on_message = 2131099694;
			
			// aapt resource value: 0x7f060022
			public const int pw_logo = 2131099682;
			
			// aapt resource value: 0x7f06002a
			public const int registered = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int registered_error = 2131099692;
			
			// aapt resource value: 0x7f06002f
			public const int second_activity = 2131099695;
			
			// aapt resource value: 0x7f060019
			public const int status_bar_notification_info_overflow = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int status_error = 2131099677;
			
			// aapt resource value: 0x7f06001a
			public const int status_init_error = 2131099674;
			
			// aapt resource value: 0x7f06001e
			public const int status_int_parse_error = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int status_ready = 2131099679;
			
			// aapt resource value: 0x7f06001b
			public const int status_started = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int status_success = 2131099676;
			
			// aapt resource value: 0x7f060027
			public const int submit_tags = 2131099687;
			
			// aapt resource value: 0x7f060023
			public const int tag_int = 2131099683;
			
			// aapt resource value: 0x7f060025
			public const int tag_int_hint = 2131099685;
			
			// aapt resource value: 0x7f060024
			public const int tag_string = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int tag_string_hint = 2131099686;
			
			// aapt resource value: 0x7f060028
			public const int tags_status = 2131099688;
			
			// aapt resource value: 0x7f06002b
			public const int unregistered = 2131099691;
			
			// aapt resource value: 0x7f06002d
			public const int unregistered_error = 2131099693;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a000c
			public const int Text = 2131361804;
			
			// aapt resource value: 0x7f0a0005
			public const int TextAppearance_Compat_Notification = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int TextAppearance_Compat_Notification_Info = 2131361798;
			
			// aapt resource value: 0x7f0a0000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131361792;
			
			// aapt resource value: 0x7f0a000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131361803;
			
			// aapt resource value: 0x7f0a0004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131361796;
			
			// aapt resource value: 0x7f0a0001
			public const int TextAppearance_Compat_Notification_Media = 2131361793;
			
			// aapt resource value: 0x7f0a0007
			public const int TextAppearance_Compat_Notification_Time = 2131361799;
			
			// aapt resource value: 0x7f0a0002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131361794;
			
			// aapt resource value: 0x7f0a0008
			public const int TextAppearance_Compat_Notification_Title = 2131361800;
			
			// aapt resource value: 0x7f0a0003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131361795;
			
			// aapt resource value: 0x7f0a0009
			public const int Widget_Compat_NotificationActionContainer = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int Widget_Compat_NotificationActionText = 2131361802;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int pw_provider_paths = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] InlineInAppView = new int[] {
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public const int InlineInAppView_disableLayoutAnimation = 1;
			
			// aapt resource value: 0
			public const int InlineInAppView_identifier = 0;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
