#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PushwooshSample.Resource", IsApplication=true)]

namespace PushwooshSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f01000d
			public const int font = 2130771981;
			
			// aapt resource value: 0x7f010006
			public const int fontProviderAuthority = 2130771974;
			
			// aapt resource value: 0x7f010009
			public const int fontProviderCerts = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int fontProviderFetchStrategy = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int fontProviderFetchTimeout = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int fontProviderPackage = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fontProviderQuery = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public const int fontStyle = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public const int fontWeight = 2130771982;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000f
			public const int common_google_signin_btn_text_dark = 2131034127;
			
			// aapt resource value: 0x7f050000
			public const int common_google_signin_btn_text_dark_default = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_google_signin_btn_text_dark_disabled = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_signin_btn_text_dark_focused = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_signin_btn_text_dark_pressed = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int common_google_signin_btn_text_light = 2131034128;
			
			// aapt resource value: 0x7f050004
			public const int common_google_signin_btn_text_light_default = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_signin_btn_text_light_disabled = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_signin_btn_text_light_focused = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_signin_btn_text_light_pressed = 2131034119;
			
			// aapt resource value: 0x7f050011
			public const int common_google_signin_btn_tint = 2131034129;
			
			// aapt resource value: 0x7f05000b
			public const int notification_action_color_filter = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int notification_icon_bg_color = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int notification_material_background_media_default_color = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int primary_text_default_material_dark = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int ripple_material_light = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int secondary_text_default_material_dark = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int secondary_text_default_material_light = 2131034126;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0004
			public const int compat_button_inset_horizontal_material = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int compat_button_inset_vertical_material = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int compat_button_padding_horizontal_material = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int compat_button_padding_vertical_material = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int compat_control_corner_material = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int notification_action_icon_size = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int notification_action_text_size = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int notification_big_circle_margin = 2131361803;
			
			// aapt resource value: 0x7f0a0001
			public const int notification_content_margin_start = 2131361793;
			
			// aapt resource value: 0x7f0a000c
			public const int notification_large_icon_height = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int notification_large_icon_width = 2131361805;
			
			// aapt resource value: 0x7f0a0002
			public const int notification_main_column_padding_top = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int notification_media_narrow_margin = 2131361795;
			
			// aapt resource value: 0x7f0a000e
			public const int notification_right_icon_size = 2131361806;
			
			// aapt resource value: 0x7f0a0000
			public const int notification_right_side_padding_top = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public const int notification_small_icon_background_padding = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int notification_small_icon_size_as_large = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int notification_subtext_size = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int notification_top_pad = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int notification_top_pad_large_text = 2131361811;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_text_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_normal_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_normal_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int googleg_disabled_color_18 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int googleg_standard_color_18 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_launcher = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int notification_action_background = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int notification_bg = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int notification_bg_low = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int notification_bg_low_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int notification_bg_low_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int notification_bg_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int notification_bg_normal_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int notification_icon_background = 2130837533;
			
			// aapt resource value: 0x7f020021
			public const int notification_template_icon_bg = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int notification_template_icon_low_bg = 2130837538;
			
			// aapt resource value: 0x7f02001e
			public const int notification_tile_bg = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int notify_panel_notification_icon_bg = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int pw_logo = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b001d
			public const int action0 = 2131427357;
			
			// aapt resource value: 0x7f0b001a
			public const int action_container = 2131427354;
			
			// aapt resource value: 0x7f0b0021
			public const int action_divider = 2131427361;
			
			// aapt resource value: 0x7f0b001b
			public const int action_image = 2131427355;
			
			// aapt resource value: 0x7f0b001c
			public const int action_text = 2131427356;
			
			// aapt resource value: 0x7f0b002b
			public const int actions = 2131427371;
			
			// aapt resource value: 0x7f0b0005
			public const int adjust_height = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int adjust_width = 2131427334;
			
			// aapt resource value: 0x7f0b000e
			public const int async = 2131427342;
			
			// aapt resource value: 0x7f0b000b
			public const int auto = 2131427339;
			
			// aapt resource value: 0x7f0b000f
			public const int blocking = 2131427343;
			
			// aapt resource value: 0x7f0b001e
			public const int cancel_action = 2131427358;
			
			// aapt resource value: 0x7f0b0026
			public const int chronometer = 2131427366;
			
			// aapt resource value: 0x7f0b000c
			public const int dark = 2131427340;
			
			// aapt resource value: 0x7f0b002d
			public const int end_padder = 2131427373;
			
			// aapt resource value: 0x7f0b0010
			public const int forever = 2131427344;
			
			// aapt resource value: 0x7f0b0014
			public const int general_status = 2131427348;
			
			// aapt resource value: 0x7f0b0028
			public const int icon = 2131427368;
			
			// aapt resource value: 0x7f0b002c
			public const int icon_group = 2131427372;
			
			// aapt resource value: 0x7f0b0008
			public const int icon_only = 2131427336;
			
			// aapt resource value: 0x7f0b0019
			public const int image = 2131427353;
			
			// aapt resource value: 0x7f0b0027
			public const int info = 2131427367;
			
			// aapt resource value: 0x7f0b0011
			public const int italic = 2131427345;
			
			// aapt resource value: 0x7f0b000d
			public const int light = 2131427341;
			
			// aapt resource value: 0x7f0b0000
			public const int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b0020
			public const int media_actions = 2131427360;
			
			// aapt resource value: 0x7f0b0007
			public const int none = 2131427335;
			
			// aapt resource value: 0x7f0b0012
			public const int normal = 2131427346;
			
			// aapt resource value: 0x7f0b002a
			public const int notification_background = 2131427370;
			
			// aapt resource value: 0x7f0b0023
			public const int notification_main_column = 2131427363;
			
			// aapt resource value: 0x7f0b0022
			public const int notification_main_column_container = 2131427362;
			
			// aapt resource value: 0x7f0b0029
			public const int right_icon = 2131427369;
			
			// aapt resource value: 0x7f0b0024
			public const int right_side = 2131427364;
			
			// aapt resource value: 0x7f0b0013
			public const int root = 2131427347;
			
			// aapt resource value: 0x7f0b0009
			public const int standard = 2131427337;
			
			// aapt resource value: 0x7f0b0015
			public const int status = 2131427349;
			
			// aapt resource value: 0x7f0b001f
			public const int status_bar_latest_event_content = 2131427359;
			
			// aapt resource value: 0x7f0b0018
			public const int submit_tags = 2131427352;
			
			// aapt resource value: 0x7f0b0016
			public const int tag_int = 2131427350;
			
			// aapt resource value: 0x7f0b0017
			public const int tag_string = 2131427351;
			
			// aapt resource value: 0x7f0b0002
			public const int text = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int text2 = 2131427331;
			
			// aapt resource value: 0x7f0b002e
			public const int text_push = 2131427374;
			
			// aapt resource value: 0x7f0b0025
			public const int time = 2131427365;
			
			// aapt resource value: 0x7f0b0004
			public const int title = 2131427332;
			
			// aapt resource value: 0x7f0b000a
			public const int wide = 2131427338;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070001
			public const int cancel_button_image_alpha = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int status_bar_notification_info_maxnum = 2131165186;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_action = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_action_tombstone = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_media_action = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_media_cancel_action = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_big_media = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_big_media_custom = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_template_big_media_narrow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_template_big_media_narrow_custom = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_custom_big = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_icon_group = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_lines_media = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_media = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_media_custom = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_part_chronometer = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_part_time = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int second = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int push_sound = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060019
			public const int app_name = 2131099673;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_enable_button = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_enable_text = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_enable_title = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_button = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_text = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_install_title = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_notification_ticker = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_unknown_issue = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_unsupported_text = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_button = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_update_text = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_update_title = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_updating_text = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_wear_update_text = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int common_open_on_phone = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_signin_button_text = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int common_signin_button_text_long = 2131099663;
			
			// aapt resource value: 0x7f060018
			public const int fcm_sender_id = 2131099672;
			
			// aapt resource value: 0x7f060021
			public const int general_status = 2131099681;
			
			// aapt resource value: 0x7f060026
			public const int on_message = 2131099686;
			
			// aapt resource value: 0x7f06001a
			public const int pw_logo = 2131099674;
			
			// aapt resource value: 0x7f060022
			public const int registered = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int registered_error = 2131099684;
			
			// aapt resource value: 0x7f060027
			public const int second_activity = 2131099687;
			
			// aapt resource value: 0x7f060011
			public const int status_bar_notification_info_overflow = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int status_error = 2131099669;
			
			// aapt resource value: 0x7f060012
			public const int status_init_error = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int status_int_parse_error = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int status_ready = 2131099671;
			
			// aapt resource value: 0x7f060013
			public const int status_started = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int status_success = 2131099668;
			
			// aapt resource value: 0x7f06001f
			public const int submit_tags = 2131099679;
			
			// aapt resource value: 0x7f06001b
			public const int tag_int = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int tag_int_hint = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int tag_string = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int tag_string_hint = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int tags_status = 2131099680;
			
			// aapt resource value: 0x7f060023
			public const int unregistered = 2131099683;
			
			// aapt resource value: 0x7f060025
			public const int unregistered_error = 2131099685;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f08000c
			public const int Text = 2131230732;
			
			// aapt resource value: 0x7f080005
			public const int TextAppearance_Compat_Notification = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Compat_Notification_Info = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131230731;
			
			// aapt resource value: 0x7f080004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int TextAppearance_Compat_Notification_Media = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int TextAppearance_Compat_Notification_Time = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int TextAppearance_Compat_Notification_Title = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131230723;
			
			// aapt resource value: 0x7f080009
			public const int Widget_Compat_NotificationActionContainer = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int Widget_Compat_NotificationActionText = 2131230730;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
