require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "xamarin-component"

COMPONENT = "pushwoosh-1.0.xam"

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "xamarin-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o -q xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do
	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{COMPONENT} \
		--name="Pushwoosh" \
		--summary="The Pushwoosh SDK for iOS makes it easier and faster to develop Pushwoosh integrated iOS apps." \
		--publisher="Pushwoosh, Inc." \
		--website="http://www.pushwoosh.com" \
		--details="Details.md" \
		--license="License.md" \
		--getting-started="GettingStarted.md" \
		--icon="icons/pushwoosh_128x128.png" \
		--icon="icons/pushwoosh_512x512.png" \
		--library="ios":"bin/Pushwoosh_iOS.dll" \
		--sample="iOS Sample. Demonstrates Pushwoosh integration on iOS.":"samples/Pushwoosh.iOS.sln"
		END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end
